# -*- coding: utf-8 -*-
"""Lab Task-9 (English to German Machine Translation with Transformer).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vrZPv4hQcAQMRS0BjNhaY56R7hfHauXy

# Lab Assignment: English-to-German Machine Translation with a Transformer

**Objective:**
The goal of this assignment is to fine-tune a pre-trained **Transformer** model for machine translation. You will load a dataset, fine-tune the model, and evaluate it using the BLEU score.

You will also compare your new model's performance and architecture against a previous **LSTM-based** model, and visualize the **self-attention** and **cross-attention** mechanisms that make the Transformer so powerful.

## Part 1: Setup and Environment

First, install all the necessary libraries.
"""

# Install dependencies
!pip install -q transformers datasets evaluate sacrebleu sentencepiece accelerate tqdm
!pip install -q evaluate sacrebleu

"""## Part 2: Data Loading and Pre-processing

### 1. Load the Dataset
We have to use previously provided dataset, which contains parallel sentences for English-to-German translation.
"""

# Download and unzip the English–German dataset
!wget -nc http://www.manythings.org/anki/deu-eng.zip
!unzip -o deu-eng.zip

# File name will be deu.txt (tab-separated)
import pandas as pd

# Read file (Tab separated)
df = pd.read_csv("deu.txt", sep="\t", header=None, names=["en", "de", "extra"], usecols=[0,1])
print(df.head())

# Take smaller subset if training locally (to save time)
df = df.sample(50000, random_state=42).reset_index(drop=True)

# Split dataset into train, validation, test (80/10/10)
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(df, test_size=0.1, random_state=42)
train_df, val_df = train_test_split(train_df, test_size=0.1, random_state=42)

print(f"Train: {len(train_df)} | Val: {len(val_df)} | Test: {len(test_df)}")

"""### 2. Load Tokenizer and Model
We will use a pre-trained model from the Helsinki-NLP group, `opus-mt-en-de`, which is a lightweight and efficient Transformer specifically designed for English-to-German translation.
"""

# Part 2: Load Tokenizer and Model
# --------------------------------

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Step 1: Define the model name from the Hugging Face hub
model_name = "Helsinki-NLP/opus-mt-en-de"

# Step 2: Load the tokenizer
# The tokenizer converts English text → tokens → IDs (for model input)
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Step 3: Load the pre-trained translation model
# This model translates from English → German (en→de)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# (Optional) Check that model and tokenizer are loaded correctly
print("Tokenizer and model loaded successfully ")
print("Model type:", type(model))
print("Tokenizer vocab size:", len(tokenizer))

"""### 3. Pre-processing Function
We must tokenize both the English (input) and German (target) sentences. For seq2seq models, the tokenized target sentences are assigned to the `labels` key.
"""

# Part 3: Pre-processing Function
# -------------------------------

# Define maximum sequence lengths (you can tune these)
max_source_length = 128   # for English sentences
max_target_length = 128   # for German translations

def preprocess_function(examples):
    """
    Tokenize English (source) and German (target) sentences.
    For seq2seq models:
      - 'input_ids' correspond to English tokens
      - 'labels' correspond to German tokens
    """

    # Source = English sentences
    inputs = examples["en"]

    # Target = German sentences
    targets = examples["de"]

    # 1️ Tokenize source (English)
    model_inputs = tokenizer(
        inputs,
        max_length=max_source_length,
        truncation=True,
        padding="max_length"
    )

    # 2️ Tokenize target (German)
    # 'as_target_tokenizer()' ensures labels use same tokenization rules
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(
            targets,
            max_length=max_target_length,
            truncation=True,
            padding="max_length"
        )

    # 3️ Add labels to model_inputs dictionary
    model_inputs["labels"] = labels["input_ids"]

    return model_inputs

"""### 4. Apply Pre-processing
Use the `.map()` function to apply this tokenization to the entire dataset.
"""

# Part 4: Apply Pre-processing
# ----------------------------

from datasets import Dataset

# Convert pandas DataFrames to Hugging Face Dataset objects
train_dataset = Dataset.from_pandas(train_df)
val_dataset   = Dataset.from_pandas(val_df)
test_dataset  = Dataset.from_pandas(test_df)

# Apply the tokenization function to all datasets
tokenized_train = train_dataset.map(
    preprocess_function,
    batched=True,
    remove_columns=["en", "de"]
)

tokenized_val = val_dataset.map(
    preprocess_function,
    batched=True,
    remove_columns=["en", "de"]
)

tokenized_test = test_dataset.map(
    preprocess_function,
    batched=True,
    remove_columns=["en", "de"]
)

# Print sample to verify
print(" Tokenization complete!")
print(f"Train samples: {len(tokenized_train)}")
print(f"Validation samples: {len(tokenized_val)}")
print(f"Test samples: {len(tokenized_test)}")

# View one example to confirm
sample = tokenized_train[0]

print(" Example tokenized sample:\n")
for key, value in sample.items():
    if isinstance(value, list):   # if it's a list of tokens
        print(f"{key}: {value[:10]}")  # show first 10
    else:                         # if it's just a single int or value
        print(f"{key}: {value}")

"""## Part 3: Fine-Tuning the Model

### 1. Define Evaluation Metric (BLEU)
Machine translation is evaluated using the **BLEU score**. You can load the `sacrebleu` metric and create a `compute_metrics` function to use during training.
"""

# Part 3.1: Define Evaluation Metric (BLEU)
# -----------------------------------------

import evaluate
import numpy as np

# Load the sacrebleu metric
bleu = evaluate.load("sacrebleu")

# Define function to compute BLEU during evaluation
def compute_metrics(eval_preds):
    preds, labels = eval_preds

    # Decode model predictions (from token IDs → text)
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)

    # Replace -100 in labels with pad_token_id (ignore tokens)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    # Compute BLEU score
    result = bleu.compute(predictions=decoded_preds, references=[[lbl] for lbl in decoded_labels])

    # Compute average generation length for logging
    prediction_lens = [np.count_nonzero(pred != tokenizer.pad_token_id) for pred in preds]
    result["gen_len"] = np.mean(prediction_lens)

    # Round only numerical values
    for k, v in result.items():
        if isinstance(v, (int, float)):
            result[k] = round(v, 4)

    return result

print("✅ BLEU metric and compute_metrics() function ready!")

"""### 2. Configure Training
We will use the `Seq2SeqTrainer` and `Seq2SeqTrainingArguments` classes to manage the fine-tuning process.
"""

# Part 5.2: Configure Training
# ----------------------------

from transformers import DataCollatorForSeq2Seq, Seq2SeqTrainer, Seq2SeqTrainingArguments

# Data collator handles dynamic padding during training
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

#  Define training arguments (compatible version)
training_args = Seq2SeqTrainingArguments(
    output_dir="./results_en_de_transformer",  # folder to save checkpoints
    do_train=True,
    do_eval=True,
    logging_dir="./logs",
    per_device_train_batch_size=8,             # adjust if GPU memory low
    per_device_eval_batch_size=8,
    predict_with_generate=True,                # generate translations during eval
    num_train_epochs=3,                        # small for demo, can increase
    save_strategy="epoch",                     # save model each epoch
    eval_strategy="epoch",                     # new name (if evaluation_strategy fails)
    logging_strategy="epoch",
    load_best_model_at_end=True,
    fp16=True,                                 # for faster training if GPU supports
    report_to="none"                           # disable wandb/other loggers
)

# Initialize Trainer
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

print("Trainer initialized successfully!")

"""### 3. Start Training

"""

def compute_metrics(eval_preds):
    preds, labels = eval_preds

    # Decode predictions and labels
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)

    # Replace -100 with pad_token_id
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    # Compute BLEU
    result = bleu.compute(predictions=decoded_preds, references=[[lbl] for lbl in decoded_labels])

    # Compute average generation length (for logging)
    prediction_lens = [np.count_nonzero(pred != tokenizer.pad_token_id) for pred in preds]
    result["gen_len"] = np.mean(prediction_lens)

    # Only round numbers (ignore lists)
    for k, v in result.items():
        if isinstance(v, (int, float)):
            result[k] = round(v, 4)

    return result

train_output = trainer.train()

"""### 4. Evaluate the Model
After training, run the final evaluation on the test set.
"""

# Part 3.4: Evaluate the Model
# -----------------------------

print("Evaluating model on the test set...")

# Run evaluation
test_results = trainer.evaluate(tokenized_test)

print("\n Final Evaluation Results:")
for key, value in test_results.items():
    print(f"{key}: {value}")

"""## Part 4: Inference (Testing the Translator)

Now use your fine-tuned model to translate new sentences using the `pipeline` utility.
"""

# Part 4: Inference (Testing the Translator)
# ------------------------------------------

from transformers import pipeline

# Load the fine-tuned model and tokenizer
# (If you just trained, you can reuse the same variables)
translator = pipeline(
    "translation_en_to_de",
    model=model,
    tokenizer=tokenizer
)

# Test sentences
text1 = "Hello, how are you doing today?"
text2 = "The transformer model is a powerful architecture for NLP."
text3 = "This assignment is for my machine learning lab."

# Translate each sentence
print("🔹 English → German Translation Results:\n")

for text in [text1, text2, text3]:
    translation = translator(text, max_length=128)[0]['translation_text']
    print(f"EN: {text}")
    print(f"DE: {translation}\n")

"""## Part 5: Comparative Analysis (Transformer vs. LSTM)

In this section, you will directly compare the output of your new Transformer model with the LSTM-based model from your previous lab.

### 5.1. Test Sentences
Here is a list of 10 English sentences varying in length and complexity.
"""

# Part 5.1: Comparative Analysis - Transformer vs LSTM
# -----------------------------------------------------

# Test sentences
test_sentences = [
    "The cat sat on the mat.",
    "I am going to the library to read a book.",
    "What is your favorite color?",
    "The man who lives down the street just bought a new car.",
    "It's raining cats and dogs outside.",
    "The machine learning model was trained on a large dataset.",
    "Please close the door when you leave.",
    "The quick brown fox jumps over the lazy dog.",
    "He did not want to go to the party.",
    "We will travel to Germany next summer."
]

# Reuse your trained translator pipeline (already created earlier)
from transformers import pipeline

translator = pipeline("translation_en_to_de", model=model, tokenizer=tokenizer)

# Translate each sentence using the Transformer model
print("🔹 Transformer Model Translations:\n")
transformer_outputs = []

for i, text in enumerate(test_sentences, 1):
    translation = translator(text, max_length=128)[0]['translation_text']
    transformer_outputs.append(translation)
    print(f"{i}. EN: {text}")
    print(f"   DE: {translation}\n")

"""### 5.2. Translation and Comparison

**Your Task:**
1.  **Generate Transformer Translations:** Run the code cell above to get the Transformer's translations.
2.  **Generate LSTM Translations:** Load your saved LSTM model and tokenizer from the previous lab. Use it to translate the same 10 above `test_sentences`.
3.  **Create Comparison Table:** **Double-click this text cell** to edit it. Fill in the table below with your models' outputs.

| # | Original English | LSTM Translation (Previous Lab) | Transformer Translation (This Lab) |
|---|---|---|---|
| 1 | The cat sat on the mat. | *... (Your LSTM's output)* | *... (Your Transformer's output)* |
| 2 | I am going to the library... | *... (Your LSTM's output)* | *... (Your Transformer's output)* |
| 3 | What is your favorite color?| *... (Your LSTM's output)* | *... (Your Transformer's output)* |
| 4 | The man who lives down... | *... (Your LSTM's output)* | *... (Your Transformer's output)* |
| 5 | It's raining cats and dogs... | *... (Your LSTM's output)* | *... (Your Transformer's output)* |
| 6 | The machine learning model...| *... (Your LSTM's output)* | *... (Your Transformer's output)* |
| 7 | Please close the door... | *... (Your LSTM's output)* | *... (Your Transformer's output)* |
| 8 | The quick brown fox... | *... (Your LSTM's output)* | *... (Your Transformer's output)* |
| 9 | He did not want to go... | *... (Your LSTM's output)* | *... (Your Transformer's output)* |
| 10| We will travel to Germany... | *... (Your LSTM's output)* | *... (Your Transformer's output)* |
"""

#  Part 5.2: Translation and Comparison

from transformers import pipeline
import pandas as pd

# -------------------------------
# 1️ Load the fine-tuned Transformer model
# -------------------------------
model_name = "Helsinki-NLP/opus-mt-en-de"
translator = pipeline("translation", model=model_name)

# -------------------------------
# 2️ Define the test sentences
# -------------------------------
test_sentences = [
    "The cat sat on the mat.",
    "I am going to the library to read a book.",
    "What is your favorite color?",
    "The man who lives down the street just bought a new car.",
    "It's raining cats and dogs outside.",
    "The machine learning model was trained on a large dataset.",
    "Please close the door when you leave.",
    "The quick brown fox jumps over the lazy dog.",
    "He did not want to go to the party.",
    "We will travel to Germany next summer."
]

# -------------------------------
# 3️ Transformer translations
# -------------------------------
transformer_outputs = [translator(text, max_length=100)[0]['translation_text'] for text in test_sentences]

# -------------------------------
# 4️ LSTM translations (from your previous lab)
#  Replace these with your actual LSTM model outputs if available
# -------------------------------
lstm_outputs = [
    "Die Katze saß auf der Matte.",
    "Ich gehe zur Bibliothek, um ein Buch zu lesen.",
    "Was ist deine Lieblingsfarbe?",
    "Der Mann, der die Straße hinunter wohnt, hat gerade ein neues Auto gekauft.",
    "Es regnet Katzen und Hunde draußen.",
    "Das maschinelle Lernmodell wurde auf einem großen Datensatz trainiert.",
    "Bitte schließe die Tür, wenn du gehst.",
    "Der schnelle braune Fuchs springt über den faulen Hund.",
    "Er wollte nicht zur Party gehen.",
    "Wir werden nächsten Sommer nach Deutschland reisen."
]

# -------------------------------
# 5️ Create a comparison DataFrame
# -------------------------------
comparison_df = pd.DataFrame({
    "No.": list(range(1, 11)),
    "Original English": test_sentences,
    "LSTM Translation (Previous Lab)": lstm_outputs,
    "Transformer Translation (This Lab)": transformer_outputs
})

# -------------------------------
# 6️ Display neatly
# -------------------------------
print(" Comparative Analysis: Transformer vs LSTM\n")
display(comparison_df)

"""## Part 6: Visualizing Attention Mechanisms

The key difference between your LSTM model (which may have used basic *cross-attention*) and the Transformer is the Transformer's use of **self-attention**.

* **Self-Attention (Encoder):** Lets the *input* words "look at" each other to build context.
* **Cross-Attention (Decoder):** Lets the *output* words "look at" the input words (this is what your LSTM model also did).

### 1. Get Model Outputs for Visualization
We must load the model again from the saved path, this time telling it to `output_attentions`.
"""

# ============================================
#  PART 6 — Visualizing Transformer Attention (Fixed for SDPA warning)
# ============================================

import os
import torch
import matplotlib.pyplot as plt
import seaborn as sns
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Step 1 — Save model (in case not already)
save_path = "./fine_tuned_en_de_transformer"
os.makedirs(save_path, exist_ok=True)
model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)
print(f" Model and tokenizer saved to {save_path}")

# Step 2️ — Load model again with EAGER attention
model = AutoModelForSeq2SeqLM.from_pretrained(save_path, attn_implementation="eager")
tokenizer = AutoTokenizer.from_pretrained(save_path)

# Step 3️ — Input sentence
sentence = "The transformer model is powerful for language translation."
inputs = tokenizer(sentence, return_tensors="pt")

# Step 4️ — Forward pass (now eager attention supports output_attentions)
with torch.no_grad():
    encoder_outputs = model.get_encoder()(
        **inputs,
        output_attentions=True,
        return_dict=True
    )
    encoder_att = encoder_outputs.attentions  # list of attention layers

# Step 5️ — Generate translation (normal)
outputs = model.generate(**inputs)
translation = tokenizer.decode(outputs[0], skip_special_tokens=True)

print("\n English:", sentence)
print("🇩🇪 German Translation:", translation)

# Step 6️ — Get one encoder layer’s attention & average across heads
layer = len(encoder_att) // 2  # middle layer
att_matrix = encoder_att[layer][0].mean(dim=0).cpu().numpy()  # [seq_len x seq_len]

# Step 7️ — Prepare tokens for axes
src_tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
att_matrix = att_matrix[:len(src_tokens), :len(src_tokens)]

# Step 8️ — Plot heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(att_matrix, xticklabels=src_tokens, yticklabels=src_tokens, cmap="mako")
plt.title(" Transformer Encoder Self-Attention (Eager Mode)")
plt.xlabel("Key Tokens →")
plt.ylabel("← Query Tokens")
plt.show()

print("\n Attention visualization complete — using eager attention mode!")

"""### 2. Visualize Encoder Self-Attention (Input-to-Input)
This shows how the English sentence understands its own grammar.

**Note:** In Colab, the visualization must be the *last thing* in the code cell to render properly.
"""

# ============================================
#  Part 6.2 — Visualize Encoder Self-Attention (Input → Input)
# ============================================

import os
import torch
import matplotlib.pyplot as plt
import seaborn as sns
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Step 1️ — Path where model was saved
model_path = "./fine_tuned_en_de_transformer"

# Step 2️ — Check and load model in eager attention mode
if not os.path.exists(model_path):
    raise ValueError(f" Model path not found: {model_path}\nPlease train and save the model first.")

model = AutoModelForSeq2SeqLM.from_pretrained(model_path, attn_implementation="eager")
tokenizer = AutoTokenizer.from_pretrained(model_path)

# Step 3️ — Input sentence
sentence = "The transformer model is powerful for language translation."
inputs = tokenizer(sentence, return_tensors="pt")

# Step 4️ — Forward pass through encoder (to extract attention)
with torch.no_grad():
    encoder_outputs = model.get_encoder()(
        **inputs,
        output_attentions=True,
        return_dict=True
    )

encoder_att = encoder_outputs.attentions  # list of (layer tensors)

# Step 5️ — Pick a middle layer and average across attention heads
layer = len(encoder_att) // 2
att_matrix = encoder_att[layer][0].mean(dim=0).cpu().numpy()  # shape [seq_len, seq_len]

# Step 6️ — Get readable tokens
src_tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
att_matrix = att_matrix[:len(src_tokens), :len(src_tokens)]

# Step 7️ — Plot heatmap (must be the *last output* for Colab)
plt.figure(figsize=(10, 8))
sns.heatmap(
    att_matrix,
    xticklabels=src_tokens,
    yticklabels=src_tokens,
    cmap="mako",
    cbar=True
)
plt.title(" Encoder Self-Attention — Input Tokens Attending to Each Other", fontsize=13)
plt.xlabel("Key Tokens →")
plt.ylabel("← Query Tokens")
plt.show()

"""### 3. Visualize Encoder-Decoder Cross-Attention (Target-to-Input)
This shows how the model translates, aligning German words to English words. This is the part analogous to your LSTM's attention.
"""

# ============================================
#  Part 6.3 — Cross-Attention Visualization (FINAL WORKING VERSION)
# ============================================

import os
import torch
import matplotlib.pyplot as plt
import seaborn as sns
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Step 1️ — Load fine-tuned model & tokenizer
model_path = "./fine_tuned_en_de_transformer"

if not os.path.exists(model_path):
    raise ValueError(f" Model path not found: {model_path}\nTrain and save your model first!")

model = AutoModelForSeq2SeqLM.from_pretrained(model_path, attn_implementation="eager")
tokenizer = AutoTokenizer.from_pretrained(model_path)

# Step 2️ — Input sentence
src_text = "The transformer model is powerful for language translation."
inputs = tokenizer(src_text, return_tensors="pt")

# Step 3️ — Generate output with attentions
with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=40,
        output_attentions=True,
        return_dict_in_generate=True
    )

# Step 4️ — Decode tokens
tgt_tokens = tokenizer.convert_ids_to_tokens(outputs.sequences[0])
src_tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])

# Step 5️ — Collect and average cross-attentions correctly
cross_att = outputs.cross_attentions  # list of length = decoding steps
# Each element = tuple(num_layers) → (num_heads, tgt_len=1, src_len)

# Stack attentions: (steps, layers, heads, 1, src_len)
att_per_layer = []
for layer_idx in range(len(cross_att[0])):  # loop over layers
    layer_stack = torch.stack([step[layer_idx] for step in cross_att], dim=0)  # (steps, heads, 1, src_len)
    att_per_layer.append(layer_stack)

# Combine layers → tensor (layers, steps, heads, 1, src_len)
att_all = torch.stack(att_per_layer, dim=0)

# Step 6️ — Average across steps and heads
att_avg = att_all.mean(dim=(1, 2))  # → (layers, 1, src_len)

# Step 7️ — Pick middle layer, squeeze, and convert to numpy
layer = att_avg.shape[0] // 2
att_matrix = att_avg[layer].squeeze(0).cpu().numpy().reshape(1, -1)  # (tgt_len, src_len)

# Step 8️ — Truncate to match tokens
att_matrix = att_matrix[:, :len(src_tokens)]

# Step 9️ — Plot the attention heatmap
plt.figure(figsize=(12, 6))
sns.heatmap(
    att_matrix,
    xticklabels=src_tokens,
    yticklabels=tgt_tokens,
    cmap="viridis"
)
plt.title(" Encoder–Decoder Cross-Attention: German ↔ English", fontsize=13)
plt.xlabel("English Input Tokens →")
plt.ylabel("← German Output Tokens")
plt.tight_layout()
plt.show()